services:
    # --------------------------------------------------------------------------------
    # Serviço do Banco de Dados (Usado em DEV e no modo SÓ-DB)
    # --------------------------------------------------------------------------------
    mongodb:
        container_name: mongodb-sumus
        image: mongo:4.4.29 # Versão compatível com x86_64

        # O serviço sobe com o perfil 'dev' OU com o perfil 'db'
        profiles:
            - dev
            - db

        ports:
            - "27018:27017"
        volumes:
            - mongo-data:/data/db
        environment:
            MONGO_INITDB_DATABASE: sumus_db

        networks:
            - sumus

    # --------------------------------------------------------------------------------
    # Serviço do Backend para Desenvolvimento (com Build)
    # --------------------------------------------------------------------------------
    backend-dev:
        container_name: backend-sumus-dev

        # O perfil 'dev' faz com que este serviço só suba se o perfil 'dev' for ativado
        profiles:
            - dev

        build:
            context: . # A raiz do projeto
            dockerfile: driver-service/Dockerfile # Localização do Dockerfile
        ports:
            - "8080:8080"

        # Depende do Mongo no Docker (que também está no perfil 'dev')
        depends_on:
            - mongodb

            #  Ativa o perfil 'dev' do Spring (application-dev.properties)
        environment:
            SPRING_PROFILES_ACTIVE: dev

        networks:
            - sumus

# Definição dos volumes persistentes
volumes:
    mongo-data:

networks:
    sumus:
        name: sumus
        driver: bridge
