services:
    # --------------------------------------------------------------------------------
    # Serviço do Banco de Dados (Usado em DEV e no modo SÓ-DB)
    # --------------------------------------------------------------------------------
    mongodb:
        container_name: mongodb-sumus
        image: mongo:latest
        
        # O serviço sobe com o perfil 'dev' OU com o perfil 'db'
        profiles:
            - dev
            - db  
            
        ports:
            - "27018:27017"
        volumes:
            - mongo-data:/data/db
        environment:
            MONGO_INITDB_DATABASE: sumus_db
        restart: always

    # --------------------------------------------------------------------------------
    # Serviço do Backend para Desenvolvimento (com Build)
    # --------------------------------------------------------------------------------
    backend-dev:
        container_name: backend-sumus-dev

        # O perfil 'dev' faz com que este serviço só suba se o perfil 'dev' for ativado
        profiles:
            - dev 

        build: . # Constrói a imagem do Dockerfile
        ports:
            - "8080:8080"
        
        # Depende do Mongo no Docker (que também está no perfil 'dev')
        depends_on:
            - mongodb 
        
        environment:
            # 1. Ativa o perfil 'dev' do Spring (application-dev.properties)
            SPRING_PROFILES_ACTIVE: dev 
            
            # 2. **CORREÇÃO:** Define a URI do MongoDB usando o NOME DO SERVIÇO ('mongodb')
            # Assim, dentro do container, ele sabe como encontrar o Mongo.
            SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/sumus_db                     
# Definição dos volumes persistentes
volumes:
    mongo-data:
