services:
    # --------------------------------------------------------------------------------
    # Banco de Dados (Runtime)
    # --------------------------------------------------------------------------------
    mongodb-sumus:
        container_name: mongodb-sumus
        image: mongo:4.4 # Versão do mongo compatível com CPUs sem suporte para instruções AVX.

        profiles:
            - dev
            - db

        ports:
            - "27018:27017"
        volumes:
            - mongo-data:/data/db
        environment:
            MONGO_INITDB_DATABASE: sumus_db

    # --------------------------------------------------------------------------------
    # Banco de Dados (Testes)
    # --------------------------------------------------------------------------------
    mongo-test-sumus:
        container_name: mongodb-sumus-test
        image: mongo:4.4

        profiles:
            - db

        environment:
            MONGO_INITDB_DATABASE: sumus_db

        ports:
            - "27019:27017"

    # --------------------------------------------------------------------------------
    # Microsserviço de Motoristas
    # --------------------------------------------------------------------------------
    driver-service:
        container_name: driver-service

        profiles:
            - dev

        build:
            context: driver-service/ 

        ports:
            - "8081:8080"

        depends_on: [mongodb-sumus]

        environment:
            SPRING_PROFILES_ACTIVE: dev

    # --------------------------------------------------------------------------------
    # Microsserviço de Passageiros
    # --------------------------------------------------------------------------------
    passenger-service:
        container_name: passenger-service

        profiles:
            - dev

        build:
            context: passenger-service/ 

        ports:
            - "8082:8080"

        depends_on: [mongodb-sumus]

        environment:
            SPRING_PROFILES_ACTIVE: dev


    # --------------------------------------------------------------------------------
    # Microsserviço de Rotas (ORS)
    # --------------------------------------------------------------------------------
    routing-service:
        container_name: routing-service

        profiles:
            - dev

        build:
            context: routing-service/ 

        ports:
            - "8083:8080"

        environment:
            SPRING_PROFILES_ACTIVE: dev


    # --------------------------------------------------------------------------------
    # Microsserviço de Autenticação
    # --------------------------------------------------------------------------------
    auth-service:
        container_name: auth-service

        profiles:
            - dev

        build:
            context: auth-service/

        ports:
            - "8083:8080"

        environment:
            SPRING_PROFILES_ACTIVE: dev

    api-gateway:
        container_name: api-gateway

        profiles:
            - dev

        build:
            context: api-gateway/ 

        depends_on: [driver-service, passenger-service]

        ports:
            - 8080:8080

# Definição dos volumes persistentes
volumes:
    mongo-data:
