services:
    # --------------------------------------------------------------------------------
    # Serviço do Banco de Dados (Usado em DEV e no modo SÓ-DB)
    # --------------------------------------------------------------------------------
    mongodb-sumus:
        container_name: mongodb-sumus
        image: mongo:4.4 # Versão do mongo compatível com CPUs sem suporte para instruções AVX.

        # O serviço sobe com o perfil 'dev' OU com o perfil 'db'
        profiles:
            - dev
            - db

        ports:
            - "27018:27017"
        volumes:
            - mongo-data:/data/db
        environment:
            MONGO_INITDB_DATABASE: sumus_db

    # --------------------------------------------------------------------------------
    # Banco de Dados de Testes (limpo e efêmero)
    # --------------------------------------------------------------------------------
    mongo-test-sumus:
        container_name: mongodb-sumus-test
        image: mongo:4.4

        # O serviço sobe com o perfil 'dev' OU com o perfil 'db'
        profiles:
            - dev
            - db

        environment:
            MONGO_INITDB_DATABASE: sumus_db

        ports:
            - "27019:27017"

    # --------------------------------------------------------------------------------
    # Microsserviço de Motoristas
    # --------------------------------------------------------------------------------
    driver-service:
        container_name: driver-service

        # O perfil 'dev' faz com que este serviço só suba se o perfil 'dev' for ativado
        profiles:
            - dev

        build:
            context: driver-service/ # A raiz do projeto (onde está o pom.xml pai)

        ports:
            - "8081:8080"

        # Depende do Mongo no Docker (que também está no perfil 'dev')
        depends_on: [mongodb-sumus]

        environment:
            # 1. Ativa o perfil 'dev' do Spring (application-dev.properties)
            SPRING_PROFILES_ACTIVE: dev

    # --------------------------------------------------------------------------------
    # Microsserviço de Passageiros
    # --------------------------------------------------------------------------------
    passenger-service:
        container_name: passenger-service

        # O perfil 'dev' faz com que este serviço só suba se o perfil 'dev' for ativado
        profiles:
            - dev

        build:
            context: passenger-service/ # A raiz do projeto (onde está o pom.xml pai)

        ports:
            - "8082:8080"

        # Depende do Mongo no Docker (que também está no perfil 'dev')
        depends_on: [mongodb-sumus]

        environment:
            # 1. Ativa o perfil 'dev' do Spring (application-dev.properties)
            SPRING_PROFILES_ACTIVE: dev

    api-gateway:
        container_name: api-gateway

        profiles:
            - dev

        build:
            context: api-gateway/ # A raiz do projeto (onde está o pom.xml pai)


        depends_on: [driver-service, passenger-service]

        ports:
            - 8080:8080

# Definição dos volumes persistentes
volumes:
    mongo-data:
